n1 = int(input("Digite um número: "))
n2 = int(input("Digite outro número: "))
soma = (n1 + n2)
sub = (n1 - n2)
multi = (n1 * n2)
div = (n1 / n2 if n2 !=0 else "Indefinido (div. por 0)")
print(f"soma:{n1} + {n2} = {soma} ")
print(f"subtração:{n1} - {n2} = {sub}")
print(f"multiplicaçao:{n1} * {n2} = {multi}")
print(f"divisão: {n1} / {n2} = {div}")